# Generated by Django 5.1.5 on 2025-01-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='avatar.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='familyrelation',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='relative',
            unique_together={('user', 'relative')},
        ),
    ]
