# Generated by Django 5.1.5 on 2025-01-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_picture_alter_familyrelation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linage_name',
            new_name='lineage_name',
        ),
    ]
