# Generated by Django 5.1.5 on 2025-01-27 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_linage_name_profile_lineage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_name', models.CharField(max_length=150)),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_offline_relative', to='profiles.familyrelation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offline_relative', to='profiles.profile')),
            ],
            options={
                'unique_together': {('user', 'relative_name')},
            },
        ),
    ]
