# Generated by Django 5.1.5 on 2025-01-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_offlinerelative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlinerelative',
            old_name='relative_name',
            new_name='relative_first_name',
        ),
        migrations.AlterUniqueTogether(
            name='offlinerelative',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offlinerelative',
            name='relative_last_name',
            field=models.CharField(default='Ade', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='offlinerelative',
            unique_together={('user', 'relative_first_name', 'relative_last_name')},
        ),
    ]
