# Generated by Django 5.1.5 on 2025-01-31 23:17

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_relative_name_offlinerelative_relative_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyrelation',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='avatar.png', upload_to='images', validators=[profiles.models.validate_image_size]),
        ),
    ]
