# Generated by Django 5.1.5 on 2025-02-03 22:03

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinerelative',
            name='picture',
            field=models.ImageField(default='avatar.png', upload_to='images', validators=[profiles.models.validate_image_size]),
        ),
    ]
