# Generated by Django 5.1.5 on 2025-02-09 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_offlinerelative_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinerelative',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='relative',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
