# Generated by Django 5.1.5 on 2025-02-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_offlinerelative_uuid_alter_profile_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinerelative',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='uuid',
        ),
    ]
