# Generated by Django 5.1.5 on 2025-02-09 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_offlinerelative_uuid_remove_profile_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinerelative',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='relative',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
