# Generated by Django 5.1.5 on 2025-02-09 16:41

from django.db import migrations
import uuid


def gen_profile_uuid(apps, schema_editor):
    MyModel = apps.get_model("profiles", "Profile")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_relative_uuid(apps, schema_editor):
    MyModel = apps.get_model("profiles", "Relative")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_offlinerelative_uuid(apps, schema_editor):
    MyModel = apps.get_model("profiles", "OfflineRelative")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_offlinerelative_uuid_profile_uuid_relative_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_profile_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_relative_uuid, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_offlinerelative_uuid, reverse_code=migrations.RunPython.noop),
    ]
