# Generated by Django 5.1.5 on 2025-02-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_offlinerelative_uuid_alter_profile_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondrequestnotification',
            old_name='relationship',
            new_name='relation',
        ),
    ]
