# Generated by Django 5.1.5 on 2025-02-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_rename_relationship_bondrequestnotification_relation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relative',
            new_name='OnlineRelative',
        ),
        migrations.AlterModelOptions(
            name='bondrequestnotification',
            options={'ordering': ['-created_at']},
        ),
    ]
