# Generated by Django 5.1.5 on 2025-02-11 22:32

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_rename_relative_onlinerelative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinerelative',
            name='picture',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='images', validators=[profiles.models.validate_image_size]),
        ),
    ]
