# Generated by Django 5.1.5 on 2025-02-12 22:21

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinerelative',
            name='picture',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='images', validators=[profiles.models.validate_image_size]),
        ),
    ]
