# Generated by Django 5.1.5 on 2025-03-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_alter_eulogy_options_alter_familyhead_options'),
        ('profiles', '0020_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_profile', to='families.family'),
        ),
    ]
