# Generated by Django 5.1.5 on 2025-05-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Baarokallohu fihi'),
            preserve_default=False,
        ),
    ]
