# Generated by Django 5.1.5 on 2025-02-15 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0020_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('origin', models.TextField()),
                ('house', models.TextField()),
                ('belief_system', models.TextField()),
                ('other_information', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('handlers', models.ManyToManyField(blank=True, related_name='family_handlers', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_head_family', to='families.family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_head_person', to='profiles.profile')),
            ],
        ),
    ]
