# Generated by Django 5.1.5 on 2025-02-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('profiles', '0020_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AddField(
            model_name='family',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_author', to='profiles.profile'),
        ),
    ]
