# Generated by Django 5.1.5 on 2025-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_options_family_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='eulogy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
