# Generated by Django 5.1.5 on 2025-02-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_family_eulogy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='house',
            new_name='family_house_info',
        ),
    ]
