# Generated by Django 5.1.5 on 2025-02-16 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_rename_house_family_family_house_info'),
        ('profiles', '0020_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='belief_system',
        ),
        migrations.RemoveField(
            model_name='family',
            name='eulogy',
        ),
        migrations.RemoveField(
            model_name='family',
            name='family_house_info',
        ),
        migrations.RemoveField(
            model_name='family',
            name='handlers',
        ),
        migrations.RemoveField(
            model_name='family',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='family',
            name='other_information',
        ),
        migrations.CreateModel(
            name='BeliefSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('details', models.TextField()),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_belief_system', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='Eulogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('details', models.TextField()),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_eulogy', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_handlers', to='families.family')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('details', models.TextField()),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_house_info', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField()),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_origin', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('details', models.TextField()),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_other_information', to='families.family')),
            ],
        ),
    ]
