# Generated by Django 5.1.5 on 2025-02-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_remove_family_belief_system_remove_family_eulogy_and_more'),
        ('profiles', '0020_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_heads', to='families.family'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_handler', to='profiles.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='handler',
            unique_together={('family', 'operator')},
        ),
    ]
