# Generated by Django 5.1.5 on 2025-02-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_alter_familyhead_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='description',
            new_name='details',
        ),
    ]
