# Generated by Django 5.1.5 on 2025-02-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0008_rename_description_origin_details'),
        ('profiles', '0020_alter_offlinerelative_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='operator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_handler', to='profiles.profile'),
        ),
    ]
