# Generated by Django 5.1.5 on 2025-03-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0009_alter_handler_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eulogy',
            options={'verbose_name_plural': 'Eulogies'},
        ),
        migrations.AlterModelOptions(
            name='familyhead',
            options={'ordering': ['date_to']},
        ),
    ]
